-- Ariel
-- Javier
-- 1. Crear tablas con restricciones NOT NULL
CREATE TABLE ESTADO (
    CODESTCTA INT PRIMARY KEY,
    DESCRIPCION VARCHAR(30) NOT NULL
);

CREATE TABLE ENTIDAD (
    COD_BCO INT PRIMARY KEY,
    BANCO VARCHAR(30) NOT NULL
);

CREATE TABLE SUCURSAL (
    COD_SUC INT PRIMARY KEY,
    SUCURSAL VARCHAR(30) NOT NULL
);

CREATE TABLE SITUACION (
    INDSITUAR INT PRIMARY KEY,
    DESCRIPCION VARCHAR(20) NOT NULL
);

CREATE TABLE PERSONA (
    RUT INT PRIMARY KEY,
    NOMBRES VARCHAR(30) NOT NULL,
    APE_PAT VARCHAR(20) NOT NULL,
    APE_MAT VARCHAR(20)
);

CREATE TABLE CUENTA (
    COD_BCO VARCHAR(4),
    COD_SUC VARCHAR(4),
    NUMCONTRATO VARCHAR(12),
    CODESTCTA INT,
    FECALTA DATE NOT NULL,
    FECBAJA DATE,
    RUT INT,
    PRIMARY KEY (COD_BCO, COD_SUC, NUMCONTRATO, CODESTCTA)
);

CREATE TABLE TARJETA (
    ENTIDAD VARCHAR(4),
    SUCURSAL VARCHAR(4),
    NUMCONTRATO VARCHAR(12),
    PAN VARCHAR(16) PRIMARY KEY,
    INDSITUAR INT NOT NULL,
    FECCADU DATE NOT NULL,
    TIPPER VARCHAR(10) NOT NULL,
    RUT INT
);

-- 2. Crear restricciones FOREIGN KEY
ALTER TABLE CUENTA ADD CONSTRAINT FK_CUENTA_ESTADO 
    FOREIGN KEY (CODESTCTA) REFERENCES ESTADO(CODESTCTA);

ALTER TABLE CUENTA ADD CONSTRAINT FK_CUENTA_PERSONA 
    FOREIGN KEY (RUT) REFERENCES PERSONA(RUT);

ALTER TABLE TARJETA ADD CONSTRAINT FK_TARJETA_SITUACION 
    FOREIGN KEY (INDSITUAR) REFERENCES SITUACION(INDSITUAR);

ALTER TABLE TARJETA ADD CONSTRAINT FK_TARJETA_PERSONA 
    FOREIGN KEY (RUT) REFERENCES PERSONA(RUT);

-- 3. Crear secuencias
-- Secuencia para ESTADO.CODESTCTA
CREATE SEQUENCE SEQ_ESTADO
    START WITH 1
    INCREMENT BY 1;

-- Secuencia para SITUACION.INDSITUAR
CREATE SEQUENCE SEQ_SITUACION
    START WITH 1
    INCREMENT BY 1;

-- Secuencia para ENTIDAD.COD_BCO
CREATE SEQUENCE SEQ_ENTIDAD
    START WITH 0
    INCREMENT BY 10;

-- Secuencia para SUCURSAL.COD_SUC
CREATE SEQUENCE SEQ_SUCURSAL
    START WITH 1
    INCREMENT BY 1;

-- 4. Insertar registros en ESTADO usando la secuencia
INSERT INTO ESTADO (CODESTCTA, DESCRIPCION) VALUES (SEQ_ESTADO.NEXTVAL, 'ACTIVA');
INSERT INTO ESTADO (CODESTCTA, DESCRIPCION) VALUES (SEQ_ESTADO.NEXTVAL, 'NO ACTIVA');
INSERT INTO ESTADO (CODESTCTA, DESCRIPCION) VALUES (SEQ_ESTADO.NEXTVAL, 'MOROSIDAD LEVE');
INSERT INTO ESTADO (CODESTCTA, DESCRIPCION) VALUES (SEQ_ESTADO.NEXTVAL, 'ACELERACIÓN');
INSERT INTO ESTADO (CODESTCTA, DESCRIPCION) VALUES (SEQ_ESTADO.NEXTVAL, 'CASTIGADA');

-- 5. Insertar registros en SITUACION usando la secuencia
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (SEQ_SITUACION.NEXTVAL, 'SOLICITADA');
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (SEQ_SITUACION.NEXTVAL, 'IMPRESA');
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (SEQ_SITUACION.NEXTVAL, 'EN PODER DEL CLIENTE');
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (SEQ_SITUACION.NEXTVAL, 'ACUSE RECIBO CLIENTE');
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (SEQ_SITUACION.NEXTVAL, 'OPERATIVA');
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (SEQ_SITUACION.NEXTVAL, 'BLOQUEADA ROBO');
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (SEQ_SITUACION.NEXTVAL, 'CADUCADA');
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (SEQ_SITUACION.NEXTVAL, 'BLOQUEDA PERDIDA');
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (SEQ_SITUACION.NEXTVAL, 'DESTRUIDA');
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (SEQ_SITUACION.NEXTVAL, 'BLOQUEADA FRAUDE');
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (SEQ_SITUACION.NEXTVAL, 'INUTILIZABLE');

-- 6. Insertar registros en ENTIDAD usando la secuencia
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES (SEQ_ENTIDAD.NEXTVAL, 'BANCOESTADO');
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES (SEQ_ENTIDAD.NEXTVAL, 'SCOTIABANK');
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES (SEQ_ENTIDAD.NEXTVAL, 'SANTANDER');
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES (SEQ_ENTIDAD.NEXTVAL, 'ITAU');
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES (SEQ_ENTIDAD.NEXTVAL, 'BANCO DE CHILE');

-- 7. Insertar registros en SUCURSAL usando la secuencia
INSERT INTO SUCURSAL (COD_SUC, SUCURSAL) VALUES (SEQ_SUCURSAL.NEXTVAL, 'SANTIAGO CENTRO 1');
INSERT INTO SUCURSAL (COD_SUC, SUCURSAL) VALUES (SEQ_SUCURSAL.NEXTVAL, 'MACUL');
INSERT INTO SUCURSAL (COD_SUC, SUCURSAL) VALUES (SEQ_SUCURSAL.NEXTVAL, 'ÑUÑOA');
INSERT INTO SUCURSAL (COD_SUC, SUCURSAL) VALUES (SEQ_SUCURSAL.NEXTVAL, 'PUENTE ALTO');
INSERT INTO SUCURSAL (COD_SUC, SUCURSAL) VALUES (SEQ_SUCURSAL.NEXTVAL, 'RENCA');

-- 8. Insertar registros en las tablas vacías (PERSONA, CUENTA, TARJETA)
-- Insertar personas
INSERT INTO PERSONA (RUT, NOMBRES, APE_PAT, APE_MAT) VALUES (12345678, 'JUAN CARLOS', 'GONZALEZ', 'PEREZ');
INSERT INTO PERSONA (RUT, NOMBRES, APE_PAT, APE_MAT) VALUES (23456789, 'MARIA ISABEL', 'LOPEZ', 'SILVA');
INSERT INTO PERSONA (RUT, NOMBRES, APE_PAT, APE_MAT) VALUES (34567890, 'PEDRO ANTONIO', 'RODRIGUEZ', 'MARTINEZ');
INSERT INTO PERSONA (RUT, NOMBRES, APE_PAT, APE_MAT) VALUES (45678901, 'ANA MARIA', 'FERNANDEZ', 'GARCIA');
INSERT INTO PERSONA (RUT, NOMBRES, APE_PAT, APE_MAT) VALUES (56789012, 'CARLOS ALBERTO', 'RAMIREZ', 'CASTILLO');

-- Insertar cuentas
INSERT INTO CUENTA (COD_BCO, COD_SUC, NUMCONTRATO, CODESTCTA, FECALTA, FECBAJA, RUT) 
VALUES ('0010', '0001', 'CTO20240001', 1, SYSDATE, NULL, 12345678);

INSERT INTO CUENTA (COD_BCO, COD_SUC, NUMCONTRATO, CODESTCTA, FECALTA, FECBAJA, RUT) 
VALUES ('0020', '0002', 'CTO20240002', 1, SYSDATE, NULL, 23456789);

INSERT INTO CUENTA (COD_BCO, COD_SUC, NUMCONTRATO, CODESTCTA, FECALTA, FECBAJA, RUT) 
VALUES ('0030', '0003', 'CTO20240003', 2, SYSDATE, NULL, 34567890);

-- Insertar tarjetas
INSERT INTO TARJETA (ENTIDAD, SUCURSAL, NUMCONTRATO, PAN, INDSITUAR, FECCADU, TIPPER, RUT) 
VALUES ('0010', '0001', 'CTO20240001', '4111111111111111', 5, TO_DATE('2026-12-31', 'YYYY-MM-DD'), 'TITULAR', 12345678);

INSERT INTO TARJETA (ENTIDAD, SUCURSAL, NUMCONTRATO, PAN, INDSITUAR, FECCADU, TIPPER, RUT) 
VALUES ('0020', '0002', 'CTO20240002', '5111111111111111', 5, TO_DATE('2027-06-30', 'YYYY-MM-DD'), 'TITULAR', 23456789);

INSERT INTO TARJETA (ENTIDAD, SUCURSAL, NUMCONTRATO, PAN, INDSITUAR, FECCADU, TIPPER, RUT) 
VALUES ('0030', '0003', 'CTO20240003', '6111111111111111', 1, TO_DATE('2028-03-15', 'YYYY-MM-DD'), 'ADICIONAL', 34567890);

-- Confirmar los cambios
COMMIT;

-- Verificar los registros insertados
SELECT 'ESTADO' AS TABLA, COUNT(*) AS CANTIDAD FROM ESTADO
UNION ALL
SELECT 'ENTIDAD', COUNT(*) FROM ENTIDAD
UNION ALL
SELECT 'SUCURSAL', COUNT(*) FROM SUCURSAL
UNION ALL
SELECT 'SITUACION', COUNT(*) FROM SITUACION
UNION ALL
SELECT 'PERSONA', COUNT(*) FROM PERSONA
UNION ALL
SELECT 'CUENTA', COUNT(*) FROM CUENTA
UNION ALL
SELECT 'TARJETA', COUNT(*) FROM TARJETA;