-- José Benjamín Vallejos Pérez
-- Villarroel

-- ERROR 4085 (HY000) at line 124: Sequence 'estado.seq_cod_bco' has out of range value for options

---- Evaluación ----
-- crear base de datos: 
-- tablas creadas: 
-- restricciones: 
-- secuencias: 
-- insertar registros: 
-- insertar (PERSONA, CUENTA, TARJETA): 
-- Confirmar: 
-- Verificar: 
--------------------

create database estado;
use estado;
-- TABLA: ESTADO
CREATE TABLE ESTADO (
    CODESTCTA INT NOT NULL,
    DESCRIPCION VARCHAR(120) NOT NULL
);


-- TABLA: SITUACION
CREATE TABLE SITUACION (
    INDSITTAR INT NOT NULL,
    DESCRIPCION VARCHAR(120) NOT NULL
);


-- TABLA: ENTIDAD
CREATE TABLE ENTIDAD (
    COD_BCO INT NOT NULL,
    BANCO VARCHAR(40) NOT NULL
);


-- TABLA: SUCURSAL
CREATE TABLE SUCURSAL (
    COD_SUC INT NOT NULL,
    SUCURSAL VARCHAR(40) NOT NULL
);


-- TABLA: PERSONA
CREATE TABLE PERSONA (
    RUT INT NOT NULL,
    NOMBRES VARCHAR(120) NOT NULL,
    APE_PAT VARCHAR(40) NOT NULL,
    APE_MAT VARCHAR(20)
);


-- TABLA: CUENTA
CREATE TABLE CUENTA (
    COD_BCO INT NOT NULL,
    COD_SUC INT NOT NULL,
    NUMCTACTE VARCHAR(12) NOT NULL,
    CODESTCTA INT NOT NULL,
    FECACTA DATE NOT NULL,
    FECHBA DATE,
    RUT INT NOT NULL
);


-- TABLA: TARJETA
CREATE TABLE TARJETA (
    ENTIDAD VARCHAR(40) NOT NULL,
    SUCURSAL VARCHAR(40) NOT NULL,
    NUMCONTAR VARCHAR(12) NOT NULL,
    PAN VARCHAR(16) NOT NULL,
    INDSITTAR INT NOT NULL,
    FECACTU DATE NOT NULL,
    TIPPER VARCHAR(10) NOT NULL,
    RUT INT NOT NULL
);


ALTER TABLE ESTADO ADD CONSTRAINT PK_ESTADO PRIMARY KEY (CODESTCTA);
ALTER TABLE SITUACION ADD CONSTRAINT PK_SITUACION PRIMARY KEY (INDSITTAR);
ALTER TABLE ENTIDAD ADD CONSTRAINT PK_ENTIDAD PRIMARY KEY (COD_BCO);
ALTER TABLE SUCURSAL ADD CONSTRAINT PK_SUCURSAL PRIMARY KEY (COD_SUC);
ALTER TABLE PERSONA ADD CONSTRAINT PK_PERSONA PRIMARY KEY (RUT);
ALTER TABLE CUENTA ADD CONSTRAINT PK_CUENTA PRIMARY KEY (COD_BCO, COD_SUC, NUMCTACTE);
ALTER TABLE TARJETA ADD CONSTRAINT PK_TARJETA PRIMARY KEY (ENTIDAD, SUCURSAL, NUMCONTAR);


ALTER TABLE CUENTA 
    ADD CONSTRAINT FK_CUENTA_ESTADO FOREIGN KEY (CODESTCTA)
    REFERENCES ESTADO(CODESTCTA);

ALTER TABLE CUENTA 
    ADD CONSTRAINT FK_CUENTA_ENTIDAD FOREIGN KEY (COD_BCO)
    REFERENCES ENTIDAD(COD_BCO);

ALTER TABLE CUENTA 
    ADD CONSTRAINT FK_CUENTA_SUCURSAL FOREIGN KEY (COD_SUC)
    REFERENCES SUCURSAL(COD_SUC);

ALTER TABLE CUENTA 
    ADD CONSTRAINT FK_CUENTA_PERSONA FOREIGN KEY (RUT)
    REFERENCES PERSONA(RUT);

ALTER TABLE TARJETA 
    ADD CONSTRAINT FK_TARJETA_SITUACION FOREIGN KEY (INDSITTAR)
    REFERENCES SITUACION(INDSITTAR);

ALTER TABLE TARJETA 
    ADD CONSTRAINT FK_TARJETA_PERSONA FOREIGN KEY (RUT)
    REFERENCES PERSONA(RUT);


-- Secuencia para ESTADO
CREATE SEQUENCE SEQ_CODESTCTA
START WITH 1
INCREMENT BY 1;

-- Secuencia para SITUACION
CREATE SEQUENCE SEQ_INDSITTAR
START WITH 1
INCREMENT BY 1;

-- Secuencia para ENTIDAD
CREATE SEQUENCE SEQ_COD_BCO
START WITH 0
INCREMENT BY 10;

-- Secuencia para SUCURSAL
CREATE SEQUENCE SEQ_COD_SUC
START WITH 1
INCREMENT BY 1;


INSERT INTO ESTADO VALUES (SEQ_CODESTCTA.NEXTVAL, 'ACTIVA');
INSERT INTO ESTADO VALUES (SEQ_CODESTCTA.NEXTVAL, 'NO ACTIVA');
INSERT INTO ESTADO VALUES (SEQ_CODESTCTA.NEXTVAL, 'MOROSIDAD LEVE');
INSERT INTO ESTADO VALUES (SEQ_CODESTCTA.NEXTVAL, 'ACELERACIÓN');
INSERT INTO ESTADO VALUES (SEQ_CODESTCTA.NEXTVAL, 'CASTIGADA');


INSERT INTO SITUACION VALUES (SEQ_INDSITTAR.NEXTVAL, 'SOLICITADA');
INSERT INTO SITUACION VALUES (SEQ_INDSITTAR.NEXTVAL, 'IMPRESA');
INSERT INTO SITUACION VALUES (SEQ_INDSITTAR.NEXTVAL, 'EN PODER DEL CLIENTE');
INSERT INTO SITUACION VALUES (SEQ_INDSITTAR.NEXTVAL, 'ACUSE RECIBO CLIENTE');
INSERT INTO SITUACION VALUES (SEQ_INDSITTAR.NEXTVAL, 'OPERATIVA');
INSERT INTO SITUACION VALUES (SEQ_INDSITTAR.NEXTVAL, 'BLOQUEADA ROBO');
INSERT INTO SITUACION VALUES (SEQ_INDSITTAR.NEXTVAL, 'CADUCADA');
INSERT INTO SITUACION VALUES (SEQ_INDSITTAR.NEXTVAL, 'BLOQUEADA PERDIDA');
INSERT INTO SITUACION VALUES (SEQ_INDSITTAR.NEXTVAL, 'DESTRUIDA');
INSERT INTO SITUACION VALUES (SEQ_INDSITTAR.NEXTVAL, 'BLOQUEADA FRAUDE');
INSERT INTO SITUACION VALUES (SEQ_INDSITTAR.NEXTVAL, 'INUTILIZABLE');

INSERT INTO ENTIDAD VALUES (SEQ_COD_BCO.NEXTVAL, 'BANCOESTADO');
INSERT INTO ENTIDAD VALUES (SEQ_COD_BCO.NEXTVAL, 'SCOTIABANK');
INSERT INTO ENTIDAD VALUES (SEQ_COD_BCO.NEXTVAL, 'SANTANDER');
INSERT INTO ENTIDAD VALUES (SEQ_COD_BCO.NEXTVAL, 'ITAU');
INSERT INTO ENTIDAD VALUES (SEQ_COD_BCO.NEXTVAL, 'BANCO DE CHILE');


INSERT INTO SUCURSAL VALUES (SEQ_COD_SUC.NEXTVAL, 'SANTIAGO CENTRO 1');
INSERT INTO SUCURSAL VALUES (SEQ_COD_SUC.NEXTVAL, 'MACUL');
INSERT INTO SUCURSAL VALUES (SEQ_COD_SUC.NEXTVAL, 'ÑUÑOA');
INSERT INTO SUCURSAL VALUES (SEQ_COD_SUC.NEXTVAL, 'PUENTE ALTO');
INSERT INTO SUCURSAL VALUES (SEQ_COD_SUC.NEXTVAL, 'RENCA');

-- Personas
INSERT INTO PERSONA VALUES (11111111, 'JUAN CARLOS', 'PEREZ', 'GOMEZ');
INSERT INTO PERSONA VALUES (22222222, 'MARIA JOSE', 'ROJAS', 'DIAZ');
INSERT INTO PERSONA VALUES (33333333, 'PEDRO', 'SALAZAR', 'SOTO');

-- Cuentas
INSERT INTO CUENTA VALUES (0, 1, '100001', 1, SYSDATE, NULL, 11111111);
INSERT INTO CUENTA VALUES (10, 2, '200001', 2, SYSDATE, NULL, 22222222);
INSERT INTO CUENTA VALUES (20, 3, '300001', 1, SYSDATE, NULL, 33333333);

-- Tarjetas
INSERT INTO TARJETA VALUES ('BANCOESTADO', 'SANTIAGO CENTRO 1', 'TARJ001', '1111222233334444', 5, SYSDATE, 'TITULAR', 11111111);
INSERT INTO TARJETA VALUES ('SCOTIABANK', 'MACUL', 'TARJ002', '5555666677778888', 1, SYSDATE, 'TITULAR', 22222222);
INSERT INTO TARJETA VALUES ('SANTANDER', 'ÑUÑOA', 'TARJ003', '9999000011112222', 2, SYSDATE, 'TITULAR', 33333333);


-- vallejos_villarroel.sql
-- Mostrando vallejos_villarroel.sql