-- Braulio Riquelme y Renato Hernandez
Create database emprendimiento;

Use emprendimiento;

-- Tabla ESTADO
CREATE TABLE ESTADO (
    CODESTCTA NUMERIC NOT NULL,
    DESCRIPCION VARCHAR(50) NOT NULL
);

-- Tabla SITUACION
CREATE TABLE SITUACION (
    INDSITTAR NUMERIC NOT NULL,
    DESCRIPCION VARCHAR(50) NOT NULL
);

-- Tabla ENTIDAD
CREATE TABLE ENTIDAD (
    COD_BCO NUMERIC NOT NULL,
    BANCO VARCHAR(50) NOT NULL
);

-- Tabla SUCURSAL
CREATE TABLE SUCURSAL (
    COD_SUC NUMERIC NOT NULL,
    SUCURSAL VARCHAR(50) NOT NULL
);

-- Tabla CLIENTE 
CREATE TABLE CLIENTE (
    RUT_CLI VARCHAR(12) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(15),
    EMAIL VARCHAR(100),
    DIRECCION VARCHAR(200)
);

-- Tabla CUENTA 
CREATE TABLE CUENTA (
    NUM_CUENTA NUMERIC NOT NULL,
    RUT_CLI VARCHAR(12) NOT NULL,
    COD_BCO NUMERIC NOT NULL,
    COD_SUC NUMERIC NOT NULL,
    CODESTCTA NUMERIC NOT NULL,
    SALDO NUMERIC(15,2) DEFAULT 0,
    FECHA_APERTURA DATE NOT NULL
);

-- Tabla TARJETA 
CREATE TABLE TARJETA (
    NUM_TARJETA VARCHAR(16) NOT NULL,
    NUM_CUENTA NUMERIC NOT NULL,
    INDSITTAR NUMERIC NOT NULL,
    FECHA_EMISION DATE NOT NULL,
    FECHA_VENCIMIENTO DATE NOT NULL,
    CVV VARCHAR(3) NOT NULL
);

-- 2. CREACIÓN DE PRIMARY KEYS
ALTER TABLE ESTADO 
ADD CONSTRAINT PK_ESTADO PRIMARY KEY (CODESTCTA);

ALTER TABLE SITUACION 
ADD CONSTRAINT PK_SITUACION PRIMARY KEY (INDSITTAR);

ALTER TABLE ENTIDAD 
ADD CONSTRAINT PK_ENTIDAD PRIMARY KEY (COD_BCO);

ALTER TABLE SUCURSAL 
ADD CONSTRAINT PK_SUCURSAL PRIMARY KEY (COD_SUC);

ALTER TABLE CLIENTE 
ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (RUT_CLI);

ALTER TABLE CUENTA 
ADD CONSTRAINT PK_CUENTA PRIMARY KEY (NUM_CUENTA);

ALTER TABLE TARJETA 
ADD CONSTRAINT PK_TARJETA PRIMARY KEY (NUM_TARJETA);

-- 3. CREACIÓN DE FOREIGN KEYS
-- CUENTA tiene relaciones con CLIENTE, ENTIDAD, SUCURSAL y ESTADO
ALTER TABLE CUENTA 
ADD CONSTRAINT FK_CUENTA_CLIENTE 
FOREIGN KEY (RUT_CLI) REFERENCES CLIENTE(RUT_CLI);

ALTER TABLE CUENTA 
ADD CONSTRAINT FK_CUENTA_ENTIDAD 
FOREIGN KEY (COD_BCO) REFERENCES ENTIDAD(COD_BCO);

ALTER TABLE CUENTA 
ADD CONSTRAINT FK_CUENTA_SUCURSAL 
FOREIGN KEY (COD_SUC) REFERENCES SUCURSAL(COD_SUC);

ALTER TABLE CUENTA 
ADD CONSTRAINT FK_CUENTA_ESTADO 
FOREIGN KEY (CODESTCTA) REFERENCES ESTADO(CODESTCTA);

-- TARJETA tiene relaciones con CUENTA y SITUACION
ALTER TABLE TARJETA 
ADD CONSTRAINT FK_TARJETA_CUENTA 
FOREIGN KEY (NUM_CUENTA) REFERENCES CUENTA(NUM_CUENTA);

ALTER TABLE TARJETA 
ADD CONSTRAINT FK_TARJETA_SITUACION 
FOREIGN KEY (INDSITTAR) REFERENCES SITUACION(INDSITTAR);

-- 4. CONFIGURAR AUTO_INCREMENT PARA ESTADO 
ALTER TABLE ESTADO AUTO_INCREMENT = 1;

-- 5. CONFIGURAR AUTO_INCREMENT PARA SITUACION
ALTER TABLE SITUACION AUTO_INCREMENT = 1;

-- 6. CONFIGURAR AUTO_INCREMENT PARA ENTIDAD
ALTER TABLE ENTIDAD AUTO_INCREMENT = 0;

-- 7. CONFIGURAR AUTO_INCREMENT PARA SUCURSAL
ALTER TABLE SUCURSAL AUTO_INCREMENT = 1;

-- 8. INSERCIÓN DE REGISTROS EN TABLA ESTADO
INSERT INTO ESTADO (DESCRIPCION) VALUES ('ACTIVA');
INSERT INTO ESTADO (DESCRIPCION) VALUES ('NO ACTIVA');
INSERT INTO ESTADO (DESCRIPCION) VALUES ('MOROSIDAD LEVE');
INSERT INTO ESTADO (DESCRIPCION) VALUES ('ACELERACIÓN');
INSERT INTO ESTADO (DESCRIPCION) VALUES ('CASTIGADA');

-- 9. INSERCIÓN DE REGISTROS EN TABLA SITUACION
INSERT INTO SITUACION (DESCRIPCION) VALUES ('SOLICITADA');
INSERT INTO SITUACION (DESCRIPCION) VALUES ('IMPRESA');
INSERT INTO SITUACION (DESCRIPCION) VALUES ('EN PODER DEL CLIENTE');
INSERT INTO SITUACION (DESCRIPCION) VALUES ('ACUSE RECIBO CLIENTE');
INSERT INTO SITUACION (DESCRIPCION) VALUES ('OPERATIVA');
INSERT INTO SITUACION (DESCRIPCION) VALUES ('BLOQUEADA ROBO');
INSERT INTO SITUACION (DESCRIPCION) VALUES ('CADUCADA');
INSERT INTO SITUACION (DESCRIPCION) VALUES ('BLOQUEDA PERDIDA');
INSERT INTO SITUACION (DESCRIPCION) VALUES ('DESTRUIDA');
INSERT INTO SITUACION (DESCRIPCION) VALUES ('BLOQUEADA FRAUDE');
INSERT INTO SITUACION (DESCRIPCION) VALUES ('INUTILIZABLE');

-- 10. INSERCIÓN DE REGISTROS EN TABLA ENTIDAD
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES (0, 'BANCOESTADO');
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES (10, 'SCOTIABANK');
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES (20, 'SANTANDER');
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES (30, 'ITAU');
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES (40, 'BANCO DE CHILE');

-- 11. INSERCIÓN DE REGISTROS EN TABLA SUCURSAL
INSERT INTO SUCURSAL (SUCURSAL) VALUES ('SANTIAGO CENTRO 1');
INSERT INTO SUCURSAL (SUCURSAL) VALUES ('MACUL');
INSERT INTO SUCURSAL (SUCURSAL) VALUES ('ÑUÑOA');
INSERT INTO SUCURSAL (SUCURSAL) VALUES ('PUENTE ALTO');
INSERT INTO SUCURSAL (SUCURSAL) VALUES ('RENCA');

-- 12. INSERCIÓN DE REGISTROS ADICIONALES
INSERT INTO CLIENTE (RUT_CLI, NOMBRE, APELLIDO, TELEFONO, EMAIL, DIRECCION)
VALUES ('12345678-9', 'Juan', 'Pérez', '912345678', 'juan.perez@email.com', 'Av. Libertador 123');

INSERT INTO CLIENTE (RUT_CLI, NOMBRE, APELLIDO, TELEFONO, EMAIL, DIRECCION)
VALUES ('98765432-1', 'María', 'González', '987654321', 'maria.gonzalez@email.com', 'Calle Principal 456');

INSERT INTO CLIENTE (RUT_CLI, NOMBRE, APELLIDO, TELEFONO, EMAIL, DIRECCION)
VALUES ('11223344-5', 'Carlos', 'Rodríguez', '911223344', 'carlos.rodriguez@email.com', 'Pasaje Los Aromos 789');

-- Insertar cuentas de ejemplo
INSERT INTO CUENTA (RUT_CLI, COD_BCO, COD_SUC, CODESTCTA, SALDO, FECHA_APERTURA)
VALUES ('12345678-9', 0, 1, 1, 500000, '2024-01-15');

INSERT INTO CUENTA (RUT_CLI, COD_BCO, COD_SUC, CODESTCTA, SALDO, FECHA_APERTURA)
VALUES ('98765432-1', 10, 2, 1, 1200000, '2024-02-20');

INSERT INTO CUENTA (RUT_CLI, COD_BCO, COD_SUC, CODESTCTA, SALDO, FECHA_APERTURA)
VALUES ('11223344-5', 20, 3, 3, 75000, '2023-11-10');

-- Insertar tarjetas de ejemplo
INSERT INTO TARJETA (NUM_TARJETA, NUM_CUENTA, INDSITTAR, FECHA_EMISION, FECHA_VENCIMIENTO, CVV)
VALUES ('4532123456789012', 1, 5, '2024-01-20', '2028-01-31', '123');

INSERT INTO TARJETA (NUM_TARJETA, NUM_CUENTA, INDSITTAR, FECHA_EMISION, FECHA_VENCIMIENTO, CVV)
VALUES ('5412345678901234', 2, 5, '2024-02-25', '2028-02-28', '456');

INSERT INTO TARJETA (NUM_TARJETA, NUM_CUENTA, INDSITTAR, FECHA_EMISION, FECHA_VENCIMIENTO, CVV)
VALUES ('4716543210987654', 3, 6, '2023-11-15', '2027-11-30', '789');}

-- Consultar todos los estados
SELECT * FROM ESTADO;

-- Consultar todas las situaciones
SELECT * FROM SITUACION;

-- Consultar todas las entidades
SELECT * FROM ENTIDAD;

-- Consultar todas las sucursales
SELECT * FROM SUCURSAL;

-- Consultar todos los clientes
SELECT * FROM CLIENTE;

-- Consultar todas las cuentas con información relacionada
SELECT c.NUM_CUENTA, cl.NOMBRE, cl.APELLIDO, e.BANCO, s.SUCURSAL, 
       est.DESCRIPCION AS ESTADO_CUENTA, c.SALDO
FROM CUENTA c
JOIN CLIENTE cl ON c.RUT_CLI = cl.RUT_CLI
JOIN ENTIDAD e ON c.COD_BCO = e.COD_BCO
JOIN SUCURSAL s ON c.COD_SUC = s.COD_SUC
JOIN ESTADO est ON c.CODESTCTA = est.CODESTCTA;

-- Consultar todas las tarjetas con información relacionada
SELECT t.NUM_TARJETA, t.NUM_CUENTA, sit.DESCRIPCION AS SITUACION_TARJETA,
       t.FECHA_EMISION, t.FECHA_VENCIMIENTO
FROM TARJETA t
JOIN SITUACION sit ON t.INDSITTAR = sit.INDSITTAR;
evaluacion_grupal_final_2.sql
Mostrando evaluacion_grupal_final_2.sql