-- Se ejecuta sin errores y sin mostrar resultados

---- Evaluación ----
-- crear base de datos: 
-- tablas creadas: 
-- restricciones: 
-- secuencias: 
-- insertar registros: 
-- insertar (PERSONA, CUENTA, TARJETA): 
-- Confirmar: 
-- Verificar: 
--------------------

DROP DATABASE IF EXISTS Banco;
CREATE DATABASE Banco;
USE Banco;

CREATE TABLE ESTADO (
    CODESTCTA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(30) NOT NULL
);

CREATE TABLE SITUACION (
    INDSITTAR INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(20) NOT NULL
);

CREATE TABLE ENTIDAD (
    COD_BCO INT NOT NULL PRIMARY KEY,
    BANCO VARCHAR(30) NOT NULL
);

CREATE TABLE SUCURSAL (
    COD_SUC INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SUCURSAL VARCHAR(30) NOT NULL,
    COD_BCO INT NOT NULL
);

CREATE TABLE PERSONA (
    RUT INT NOT NULL PRIMARY KEY,
    NOMBRES VARCHAR(30) NOT NULL,
    APE_PAT VARCHAR(20) NOT NULL,
    APE_MAT VARCHAR(20)
);

CREATE TABLE CUENTA (
    COD_BCO VARCHAR(4) NOT NULL,
    COD_SUC VARCHAR(4) NOT NULL,
    NUMCONTRATO VARCHAR(12) NOT NULL,
    CODESTCTA INT NOT NULL,
    FECALTA DATE NOT NULL,
    FECBAJA DATE,
    RUT INT,
    PRIMARY KEY (COD_BCO, COD_SUC, NUMCONTRATO)
);

CREATE TABLE TARJETA (
    ENTIDAD VARCHAR(4) NOT NULL,
    SUCURSAL VARCHAR(4) NOT NULL,
    NUMCONTRATO VARCHAR(12) NOT NULL,
    PAN VARCHAR(16) NOT NULL,
    INDSITTAR INT NOT NULL,
    FECCADU DATE NOT NULL,
    TIPPER VARCHAR(10) NOT NULL,
    RUT INT,
    PRIMARY KEY (ENTIDAD, SUCURSAL, NUMCONTRATO, PAN)
);

ALTER TABLE SUCURSAL ADD CONSTRAINT FK_SUCURSAL_ENTIDAD 
    FOREIGN KEY (COD_BCO) REFERENCES ENTIDAD(COD_BCO);

ALTER TABLE CUENTA ADD CONSTRAINT FK_CUENTA_ESTADO
    FOREIGN KEY (CODESTCTA) REFERENCES ESTADO(CODESTCTA);

ALTER TABLE CUENTA ADD CONSTRAINT FK_CUENTA_PERSONA
    FOREIGN KEY (RUT) REFERENCES PERSONA(RUT);

ALTER TABLE TARJETA ADD CONSTRAINT FK_TARJETA_SITUACION
    FOREIGN KEY (INDSITTAR) REFERENCES SITUACION(INDSITTAR);

ALTER TABLE TARJETA ADD CONSTRAINT FK_TARJETA_PERSONA
    FOREIGN KEY (RUT) REFERENCES PERSONA(RUT);

INSERT INTO ESTADO (DESCRIPCION) VALUES
('ACTIVA'),
('NO ACTIVA'),
('MOROSIDAD LEVE'),
('ACELERACIÓN'),
('CASTIGADA');

INSERT INTO SITUACION (DESCRIPCION) VALUES
('SOLICITADA'),
('IMPRESA'),
('EN PODER DEL CLIENTE'),
('ACUSE RECIBO CLIENTE'),
('OPERATIVA'),
('BLOQUEADA ROBO'),
('CADUCADA'),
('BLOQUEDA PERDIDA'),
('DESTRUIDA'),
('BLOQUEADA FRAUDE'),
('INUTILIZABLE');

INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES
(0, 'BANCOESTADO'),
(10, 'SCOTIABANK'),
(20, 'SANTANDER'),
(30, 'ITAU'),
(40, 'BANCO DE CHILE');

INSERT INTO SUCURSAL (COD_SUC, SUCURSAL, COD_BCO) VALUES
(1, 'SANTIAGO CENTRO 1', 0),
(2, 'MACUL', 10),
(3, 'ÑUÑOA', 20),
(4, 'PUENTE ALTO', 30),
(5, 'RENCA', 40);

ALTER TABLE SUCURSAL AUTO_INCREMENT = 6;

INSERT INTO PERSONA (RUT, NOMBRES, APE_PAT, APE_MAT) VALUES
(12345678, 'JUAN', 'PEREZ', 'GOMEZ'),
(98765432, 'MARIA', 'GONZALEZ', 'ROJAS');

INSERT INTO CUENTA (COD_BCO, COD_SUC, NUMCONTRATO, CODESTCTA, FECALTA, RUT) VALUES
('0000', '0001', '123456789012', 1, '2023-01-01', 12345678),
('0010', '0002', '234567890123', 1, '2023-02-15', 98765432);

INSERT INTO TARJETA (ENTIDAD, SUCURSAL, NUMCONTRATO, PAN, INDSITTAR, FECCADU, TIPPER, RUT) VALUES
('0000', '0001', '123456789012', '4532123456789012', 5, '2026-01-31', 'DEBITO', 12345678),
('0010', '0002', '234567890123', '4916234567890123', 5, '2027-02-28', 'CREDITO', 98765432);
-- prueba2.sql
-- Mostrando prueba2.sql