-- yemina muñoz 
-- bryan vallejos
CREATE DATABASE IF NOT EXISTS evaluacion_grupal
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;
USE evaluacion_grupal;

-- TABLA: ESTADO --
CREATE TABLE ESTADO (
  CODESTCTA INT NOT NULL AUTO_INCREMENT,
  DESCRIPCION VARCHAR(50) NOT NULL,
  PRIMARY KEY (CODESTCTA)
);


-- TABLA: SITUACION
CREATE TABLE SITUACION (
  INDSITTAR INT NOT NULL AUTO_INCREMENT,
  DESCRIPCION VARCHAR(50) NOT NULL,
  PRIMARY KEY (INDSITTAR)
);


-- TABLA: ENTIDAD
-- (Sin AUTO_INCREMENT para permitir insertar los códigos 0, 10, 20, 30, 40 como en la guía)
CREATE TABLE ENTIDAD (
  COD_BCO INT NOT NULL,
  BANCO VARCHAR(50) NOT NULL,
  PRIMARY KEY (COD_BCO)
);


-- TABLA: SUCURSAL
CREATE TABLE SUCURSAL (
  COD_SUC INT NOT NULL AUTO_INCREMENT,
  SUCURSAL VARCHAR(50) NOT NULL,
  COD_BCO INT NOT NULL,
  PRIMARY KEY (COD_SUC),
  FOREIGN KEY (COD_BCO) REFERENCES ENTIDAD(COD_BCO)
);

-- Forzar que los IDs de sucursal comiencen en 1
ALTER TABLE SUCURSAL AUTO_INCREMENT = 1;


-- TABLA: PERSONA
CREATE TABLE PERSONA (
  RUT INT NOT NULL,
  NOMBRES VARCHAR(40) NOT NULL,
  APE_PAT VARCHAR(20) NOT NULL,
  APE_MAT VARCHAR(20),
  PRIMARY KEY (RUT)
);


-- TABLA: CUENTA
CREATE TABLE CUENTA (
  COD_BCO INT NOT NULL,
  COD_SUC INT NOT NULL,
  NUMCUENTA VARCHAR(12) NOT NULL,
  CODESTCTA INT NOT NULL,
  FECALTA DATE NOT NULL,
  FREBAJA DATE,
  RUT INT NOT NULL,
  PRIMARY KEY (COD_BCO, COD_SUC, NUMCUENTA),
  FOREIGN KEY (CODESTCTA) REFERENCES ESTADO(CODESTCTA),
  FOREIGN KEY (COD_BCO) REFERENCES ENTIDAD(COD_BCO),
  FOREIGN KEY (COD_SUC) REFERENCES SUCURSAL(COD_SUC),
  FOREIGN KEY (RUT) REFERENCES PERSONA(RUT)
);


-- TABLA: TARJETA
CREATE TABLE TARJETA (
  ENTIDAD VARCHAR(15) NOT NULL,
  SUCURSAL VARCHAR(25) NOT NULL,
  NUM_CONTRATO VARCHAR(12) NOT NULL,
  PAN VARCHAR(15) NOT NULL,
  INDSITTAR INT NOT NULL,
  FECADU DATE NOT NULL,
  TIPCAR VARCHAR(10),
  RUT INT NOT NULL,
  PRIMARY KEY (ENTIDAD, SUCURSAL, NUM_CONTRATO, PAN),
  FOREIGN KEY (INDSITTAR) REFERENCES SITUACION(INDSITTAR),
  FOREIGN KEY (RUT) REFERENCES PERSONA(RUT)
);


-- INSERCIÓN DE DATOS

-- 1️ ESTADO
INSERT INTO ESTADO (DESCRIPCION) VALUES
('ACTIVA'),
('NO ACTIVA'),
('MOROSIDAD LEVE'),
('ACELERACIÓN'),
('CASTIGADA');

-- 2️ SITUACION
INSERT INTO SITUACION (DESCRIPCION) VALUES
('SOLICITADA'),
('IMPRESA'),
('EN PODER DEL CLIENTE'),
('ACUSE RECIBO CLIENTE'),
('OPERATIVA'),
('BLOQUEADA ROBO'),
('CADUCADA'),
('BLOQUEADA PERDIDA'),
('DESTRUIDA'),
('BLOQUEADA FRAUDE'),
('INUTILIZABLE');

-- 3 ENTIDAD (Bancos)
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES
(0, 'BANCOESTADO'),
(10, 'SCOTIABANK'),
(20, 'SANTANDER'),
(30, 'ITAU'),
(40, 'BANCO DE CHILE');

-- 4 SUCURSAL (funciona correctamente ahora)
INSERT INTO SUCURSAL (SUCURSAL, COD_BCO) VALUES
('SANTIAGO CENTRO 1', 0),
('MACUL', 0),
('ÑUÑOA', 10),
('PUENTE ALTO', 20),
('RENCA', 30);

-- 5 ERSONA (ejemplos de clientes)
INSERT INTO PERSONA (RUT, NOMBRES, APE_PAT, APE_MAT) VALUES
(12345678, 'JUAN', 'PÉREZ', 'GÓMEZ'),
(87654321, 'MARÍA', 'ROJAS', 'SALAZAR');

-- 6CUENTA (ejemplos)
INSERT INTO CUENTA (COD_BCO, COD_SUC, NUMCUENTA, CODESTCTA, FECALTA, FREBAJA, RUT)
VALUES
(0, 1, '000111222333', 1, '2024-05-01', NULL, 12345678),
(10, 3, '111222333444', 2, '2024-06-15', NULL, 87654321);

-- TARJETA (ejemplos)
INSERT INTO TARJETA (ENTIDAD, SUCURSAL, NUM_CONTRATO, PAN, INDSITTAR, FECADU, TIPCAR, RUT)
VALUES
('BANCOESTADO', 'SANTIAGO CENTRO 1', 'T001', '123456789012345', 5, '2027-05-01', 'DÉBITO', 12345678),
('SCOTIABANK', 'ÑUÑOA', 'T002', '987654321098765', 6, '2028-03-15', 'CRÉDITO', 87654321);

prueba_grupal.sql
Mostrando prueba_grupal.sql