-- De Martín González y Francisca Herrera
create database datosrelacional;
use datosrelacional;

CREATE TABLE ESTADO (
    CODESTCTA INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(30) NOT NULL
);

CREATE TABLE SITUACION (
    INDSITTAR INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(30) NOT NULL
);

CREATE TABLE ENTIDAD (
    COD_BCO INT PRIMARY KEY,
    BANCO VARCHAR(30) NOT NULL
);

CREATE TABLE SUCURSAL (
    COD_SUC INT AUTO_INCREMENT PRIMARY KEY,
    SUCURSAL VARCHAR(30) NOT NULL
);

CREATE TABLE PERSONA (
    RUT INT PRIMARY KEY,
    NOMBRES VARCHAR(30) NOT NULL,
    APE_PAT VARCHAR(20) NOT NULL,
    APE_MAT VARCHAR(20)
);

CREATE TABLE CUENTA (
    COD_BCO INT NOT NULL,
    COD_SUC INT NOT NULL,
    NUMCONTRATO VARCHAR(12) NOT NULL,
    CODESTCTA INT NOT NULL,
    FECALTA DATE NOT NULL,
    FECBAJA DATE,
    RUT INT NOT NULL,
    CONSTRAINT PK_CUENTA PRIMARY KEY (COD_BCO, COD_SUC, NUMCONTRATO),
    CONSTRAINT FK_CUENTA_ESTADO FOREIGN KEY (CODESTCTA) REFERENCES ESTADO(CODESTCTA),
    CONSTRAINT FK_CUENTA_ENTIDAD FOREIGN KEY (COD_BCO) REFERENCES ENTIDAD(COD_BCO),
    CONSTRAINT FK_CUENTA_SUCURSAL FOREIGN KEY (COD_SUC) REFERENCES SUCURSAL(COD_SUC),
    CONSTRAINT FK_CUENTA_PERSONA FOREIGN KEY (RUT) REFERENCES PERSONA(RUT)
);

CREATE TABLE TARJETA (
    ENTIDAD INT NOT NULL,
    SUCURSAL INT NOT NULL,
    NUMCONTRATO VARCHAR(12) NOT NULL,
    PAN VARCHAR(16) PRIMARY KEY,
    INDSITTAR INT NOT NULL,
    FECCADU DATE NOT NULL,
    TIPPER VARCHAR(10) NOT NULL,
    RUT INT NOT NULL,
    CONSTRAINT FK_TARJETA_SITUACION FOREIGN KEY (INDSITTAR) REFERENCES SITUACION(INDSITTAR),
    CONSTRAINT FK_TARJETA_CUENTA FOREIGN KEY (ENTIDAD, SUCURSAL, NUMCONTRATO)
        REFERENCES CUENTA(COD_BCO, COD_SUC, NUMCONTRATO),
    CONSTRAINT FK_TARJETA_PERSONA FOREIGN KEY (RUT) REFERENCES PERSONA(RUT)
);

-- TABLA ESTADO (AUTO_INCREMENT simula secuencia desde 1, +1)
INSERT INTO ESTADO (DESCRIPCION) VALUES
('ACTIVA'),
('NO ACTIVA'),
('MOROSIDAD LEVE'),
('ACELERACIÓN'),
('CASTIGADA');

-- TABLA SITUACION (AUTO_INCREMENT simula secuencia desde 1, +1)
INSERT INTO SITUACION (DESCRIPCION) VALUES
('SOLICITADA'),
('IMPRESA'),
('EN PODER DEL CLIENTE'),
('ACUSE RECIBO CLIENTE'),
('OPERATIVA'),
('BLOQUEADA ROBO'),
('CADUCADA'),
('BLOQUEADA PERDIDA'),
('DESTRUIDA'),
('BLOQUEADA FRAUDE'),
('INUTILIZABLE');

-- TABLA ENTIDAD (manual, simula secuencia desde 0, +10)
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES
(0, 'BANCOESTADO'),
(10, 'SCOTIABANK'),
(20, 'SANTANDER'),
(30, 'ITAU'),
(40, 'BANCO DE CHILE');

-- TABLA SUCURSAL (AUTO_INCREMENT simula secuencia desde 1, +1)
INSERT INTO SUCURSAL (SUCURSAL) VALUES
('SANTIAGO CENTRO 1'),
('MACUL'),
('ÑUÑOA'),
('PUENTE ALTO'),
('RENCA');

INSERT INTO PERSONA (RUT, NOMBRES, APE_PAT, APE_MAT) VALUES
(11111111, 'JUAN', 'PEREZ', 'SOTO'),
(22222222, 'MARIA', 'GONZALEZ', 'TORRES');

INSERT INTO CUENTA (COD_BCO, COD_SUC, NUMCONTRATO, CODESTCTA, FECALTA, FECBAJA, RUT) VALUES
(0, 1, '000001', 1, CURDATE(), NULL, 11111111),
(10, 2, '000002', 2, CURDATE(), NULL, 22222222);

INSERT INTO TARJETA (ENTIDAD, SUCURSAL, NUMCONTRATO, PAN, INDSITTAR, FECCADU, TIPPER, RUT) VALUES
(0, 1, '000001', '1234567890123456', 5, '2028-12-31', 'DEBITO', 11111111),
(10, 2, '000002', '9876543210987654', 5, '2027-11-30', 'CREDITO', 22222222);

SELECT * FROM ESTADO;
SELECT * FROM SITUACION;
SELECT * FROM ENTIDAD;
SELECT * FROM SUCURSAL;
SELECT * FROM PERSONA;
SELECT * FROM CUENTA;
SELECT * FROM TARJETA;
ultima_evaluacion.sql
Mostrando ultima_evaluacion.sql