-- Anais Alcaino y Maria Fernanda Adrianzen
create database prueba;
use prueba;

CREATE TABLE ESTADO (
    CODESTCTA INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(30) NOT NULL
) AUTO_INCREMENT = 1;


CREATE TABLE SITUACION (
    INDSITTAR INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(20) NOT NULL
) AUTO_INCREMENT = 1;


CREATE TABLE ENTIDAD (
    COD_BCO INT PRIMARY KEY AUTO_INCREMENT,
    BANCO VARCHAR(30) NOT NULL
) AUTO_INCREMENT = 0;


CREATE TABLE SUCURSAL (
    COD_SUC INT PRIMARY KEY AUTO_INCREMENT,
    SUCURSAL VARCHAR(30) NOT NULL,
    COD_BCO INT NOT NULL,
    FOREIGN KEY (COD_BCO) REFERENCES ENTIDAD (COD_BCO)
) AUTO_INCREMENT = 1;


CREATE TABLE PERSONA (
    RUT INT PRIMARY KEY,
    NOMBRES VARCHAR(30) NOT NULL,
    APE_PAT VARCHAR(20) NOT NULL,
    APE_MAT VARCHAR(20)
);


CREATE TABLE CUENTA (
    COD_BCO INT NOT NULL,
    COD_SUC INT NOT NULL,
    NUMCONTRATO VARCHAR(12) NOT NULL,
    CODESTCTA INT NOT NULL,
    FECALTA DATE NOT NULL,
    FECBAJA DATE,
    RUT INT NOT NULL,
    PRIMARY KEY (COD_BCO, COD_SUC, NUMCONTRATO),
    FOREIGN KEY (COD_BCO) REFERENCES ENTIDAD (COD_BCO),
    FOREIGN KEY (COD_SUC) REFERENCES SUCURSAL (COD_SUC),
    FOREIGN KEY (CODESTCTA) REFERENCES ESTADO (CODESTCTA),
    FOREIGN KEY (RUT) REFERENCES PERSONA (RUT)
);


CREATE TABLE TARJETA (
    ENTIDAD INT NOT NULL,
    SUCURSAL INT NOT NULL,
    NUMCONTRATO VARCHAR(12) NOT NULL,
    PAN VARCHAR(16) PRIMARY KEY,
    INDSITTAR INT NOT NULL,
    FECCADU DATE NOT NULL,
    TIPPER VARCHAR(10) NOT NULL,
    RUT INT NOT NULL,
    FOREIGN KEY (ENTIDAD) REFERENCES ENTIDAD (COD_BCO),
    FOREIGN KEY (SUCURSAL) REFERENCES SUCURSAL (COD_SUC),
    FOREIGN KEY (INDSITTAR) REFERENCES SITUACION (INDSITTAR),
    FOREIGN KEY (RUT) REFERENCES PERSONA (RUT),
    FOREIGN KEY (ENTIDAD, SUCURSAL, NUMCONTRATO)
        REFERENCES CUENTA (COD_BCO, COD_SUC, NUMCONTRATO)
);


INSERT INTO ESTADO (DESCRIPCION) VALUES
('ACTIVA'),
('NO ACTIVA'),
('MOROSIDAD LEVE'),
('ACELERACIÓN'),
('CASTIGADA');


INSERT INTO SITUACION (DESCRIPCION) VALUES
('SOLICITADA'),
('IMPRESA'),
('EN PODER DEL CLIENTE'),
('ACUSE RECIBO CLIENTE'),
('OPERATIVA'),
('BLOQUEADA ROBO'),
('CADUCADA'),
('BLOQUEADA PERDIDA'),
('DESTRUIDA'),
('BLOQUEADA FRAUDE'),
('INUTILIZABLE');

SET @@auto_increment_increment = 10;

INSERT INTO ENTIDAD (BANCO) VALUES
('BANCOESTADO'),
('SCOTIABANK'),
('SANTANDER'),
('ITAU'),
('BANCO DE CHILE');

SET @@auto_increment_increment = 1;

INSERT INTO SUCURSAL (SUCURSAL, COD_BCO) VALUES
('SANTIAGO CENTRO 1', 1),
('MACUL', 1),
('ÑUÑOA', 1),
('PUENTE ALTO', 1),
('RENCA', 1);



INSERT INTO PERSONA (RUT, NOMBRES, APE_PAT, APE_MAT) VALUES
(11111111, 'JUAN', 'PEREZ', 'GONZALEZ'),
(22222222, 'MARIA', 'ROJAS', 'SOTO'),
(33333333, 'CARLOS', 'DIAZ', 'HERRERA'),
(44444444, 'ANA', 'TORRES', 'RAMIREZ');


INSERT INTO CUENTA (COD_BCO, COD_SUC, NUMCONTRATO, CODESTCTA, FECALTA, FECBAJA, RUT) VALUES
(1, 1, 'C001', 1, '2023-01-10', NULL, 11111111),
(1, 2, 'C002', 1, '2023-02-15', NULL, 22222222),
(1, 3, 'C003', 2, '2023-03-20', NULL, 33333333),
(1, 4, 'C004', 3, '2023-04-05', NULL, 44444444);


INSERT INTO TARJETA (ENTIDAD, SUCURSAL, NUMCONTRATO, PAN, INDSITTAR, FECCADU, TIPPER, RUT) VALUES
(1, 1, 'C001', '1111222233334444', 5, '2027-01-01', 'CREDITO', 11111111),
(1, 2, 'C002', '5555666677778888', 5, '2027-02-01', 'DEBITO', 22222222),
(1, 3, 'C003', '9999000011112222', 6, '2026-11-15', 'CREDITO', 33333333),
(1, 4, 'C004', '3333444455556666', 10, '2025-08-10', 'DEBITO', 44444444);

PRUEBA2025.sql
Mostrando PRUEBA2025.sql