--  Isidora Paz Retamal Díaz
-- 1. Creación de Tablas y Restricciones NOT NULL

-- Tabla ESTADO
CREATE TABLE ESTADO (
    CODESTCTA INT NOT NULL, -- PK
    DESCRIPCION VARCHAR(30) NOT NULL
);

-- Tabla ENTIDAD
CREATE TABLE ENTIDAD (
    COD_BCO INT NOT NULL, -- PK
    BANCO VARCHAR(30) NOT NULL
);

-- Tabla SUCURSAL
CREATE TABLE SUCURSAL (
    COD_BCO INT NOT NULL, -- FK PK
    COD_SUC INT NOT NULL, -- PK
    SUCURSAL VARCHAR(30) NOT NULL
);

-- Tabla SITUACION
CREATE TABLE SITUACION (
    INDSITTAR INT NOT NULL, -- PK
    DESCRIPCION VARCHAR(20) NOT NULL
);

-- Tabla PERSONA
CREATE TABLE PERSONA (
    RUT INT NOT NULL, -- PK
    NOMBRES VARCHAR(30) NOT NULL,
    APE_PAT VARCHAR(20) NOT NULL,
    APE_MAT VARCHAR(20)
);

-- Tabla CUENTA
CREATE TABLE CUENTA (
    COD_BCO INT NOT NULL,     -- FK PK
    COD_SUC INT NOT NULL,     -- FK PK
    NUMCONTRATO VARCHAR(12) NOT NULL, -- PK
    CODESTCTA INT NOT NULL,   -- FK
    FECALTA DATE NOT NULL,
    FECBAJA DATE,
    RUT INT                   -- FK
    -- NOTA: El campo RUT no tiene NOT NULL en el modelo, por lo que se asume que puede ser NULL.
);

-- Tabla TARJETA
CREATE TABLE TARJETA (
    ENTIDAD VARCHAR(4) NOT NULL,      -- FK PK
    SUCURSAL VARCHAR(4) NOT NULL,     -- FK PK
    NUMCONTRATO VARCHAR(12) NOT NULL, -- FK PK
    PAN VARCHAR(16) NOT NULL,         -- PK
    INDSITTAR INT NOT NULL,           -- FK
    FECADDU DATE NOT NULL,
    TIPPER VARCHAR(10) NOT NULL,
    RUT INT                           -- FK
    -- NOTA: El campo RUT no tiene NOT NULL en el modelo, por lo que se asume que puede ser NULL.
);

-- 2. Creación de Restricciones PRIMARY KEY

-- Restricciones PRIMARY KEY
ALTER TABLE ESTADO ADD CONSTRAINT PK_ESTADO PRIMARY KEY (CODESTCTA);
ALTER TABLE ENTIDAD ADD CONSTRAINT PK_ENTIDAD PRIMARY KEY (COD_BCO);
ALTER TABLE SITUACION ADD CONSTRAINT PK_SITUACION PRIMARY KEY (INDSITTAR);
ALTER TABLE PERSONA ADD CONSTRAINT PK_PERSONA PRIMARY KEY (RUT);

-- Claves compuestas
ALTER TABLE SUCURSAL ADD CONSTRAINT PK_SUCURSAL PRIMARY KEY (COD_BCO, COD_SUC);
ALTER TABLE CUENTA ADD CONSTRAINT PK_CUENTA PRIMARY KEY (COD_BCO, COD_SUC, NUMCONTRATO);
ALTER TABLE TARJETA ADD CONSTRAINT PK_TARJETA PRIMARY KEY (ENTIDAD, SUCURSAL, NUMCONTRATO, PAN);

-- 3. Creación de Restricciones FOREIGN KEY

-- Restricciones FOREIGN KEY

-- Tabla SUCURSAL
ALTER TABLE SUCURSAL
ADD CONSTRAINT FK_SUCURSAL_ENTIDAD FOREIGN KEY (COD_BCO)
REFERENCES ENTIDAD (COD_BCO);

-- Tabla CUENTA
ALTER TABLE CUENTA
ADD CONSTRAINT FK_CUENTA_SUCURSAL FOREIGN KEY (COD_BCO, COD_SUC)
REFERENCES SUCURSAL (COD_BCO, COD_SUC);

ALTER TABLE CUENTA
ADD CONSTRAINT FK_CUENTA_ESTADO FOREIGN KEY (CODESTCTA)
REFERENCES ESTADO (CODESTCTA);

ALTER TABLE CUENTA
ADD CONSTRAINT FK_CUENTA_PERSONA FOREIGN KEY (RUT)
REFERENCES PERSONA (RUT);

-- Tabla TARJETA
-- NOTA: Se asume que ENTIDAD, SUCURSAL y NUMCONTRATO en TARJETA se refieren a los mismos campos en CUENTA
ALTER TABLE TARJETA
ADD CONSTRAINT FK_TARJETA_CUENTA FOREIGN KEY (ENTIDAD, SUCURSAL, NUMCONTRATO)
REFERENCES CUENTA (COD_BCO, COD_SUC, NUMCONTRATO);

ALTER TABLE TARJETA
ADD CONSTRAINT FK_TARJETA_SITUACION FOREIGN KEY (INDSITTAR)
REFERENCES SITUACION (INDSITTAR);

ALTER TABLE TARJETA
ADD CONSTRAINT FK_TARJETA_PERSONA FOREIGN KEY (RUT)
REFERENCES PERSONA (RUT);

-- 4. Creación de Secuencias

-- Secuencia para ESTADO.CODESTCTA (Incremento 1, Comienza en 1)
CREATE SEQUENCE SEQ_ESTADO_CODESTCTA
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCYCLE;

-- Secuencia para SITUACION.INDSITTAR (Incremento 1, Comienza en 1)
CREATE SEQUENCE SEQ_SITUACION_INDSITTAR
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCYCLE;

-- Secuencia para ENTIDAD.COD_BCO (Comienza en 0, Incremento 10)
CREATE SEQUENCE SEQ_ENTIDAD_COD_BCO
START WITH 0
INCREMENT BY 10
MINVALUE 0
NOCYCLE;

-- Secuencia para SUCURSAL.COD_SUC (Incremento 1)
-- NOTA: Se asume que comienza en 1 y no tiene límite superior si no se especifica.
CREATE SEQUENCE SEQ_SUCURSAL_COD_SUC
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCYCLE;

-- 5. Inserción de Registros

-- 5.1. Inserción en ESTADO: Se insertan los registros en la tabla ESTADO.
-- Inserción en ESTADO (CODESTCTA, DESCRIPCION)
INSERT INTO ESTADO (CODESTCTA, DESCRIPCION) VALUES (SEQ_ESTADO_CODESTCTA.NEXTVAL, 'ACTIVA');             -- Debería ser 1
INSERT INTO ESTADO (CODESTCTA, DESCRIPCION) VALUES (SEQ_ESTADO_CODESTCTA.NEXTVAL, 'NO ACTIVA');          -- Debería ser 2
INSERT INTO ESTADO (CODESTCTA, DESCRIPCION) VALUES (SEQ_ESTADO_CODESTCTA.NEXTVAL, 'MOROSIDAD LEVE');     -- Debería ser 3
INSERT INTO ESTADO (CODESTCTA, DESCRIPCION) VALUES (SEQ_ESTADO_CODESTCTA.NEXTVAL, 'ACELERACIÓN');        -- Debería ser 4
INSERT INTO ESTADO (CODESTCTA, DESCRIPCION) VALUES (SEQ_ESTADO_CODESTCTA.NEXTVAL, 'CASTIGADA');          -- Debería ser 5

-- 5.2. Inserción en SITUACION Se insertan los registros en la tabla SITUACION.
-- Inserción en SITUACION (INDSITTAR, DESCRIPCION)
INSERT INTO SITUACION (INDSITTAR, DESCRIPCION) VALUES (SEQ_SITUACION_INDSITTAR.NEXTVAL, 'SOLICITADA');
INSERT INTO SITUACION (INDSITTAR, DESCRIPCION) VALUES (SEQ_SITUACION_INDSITTAR.NEXTVAL, 'IMPRESA');
INSERT INTO SITUACION (INDSITTAR, DESCRIPCION) VALUES (SEQ_SITUACION_INDSITTAR.NEXTVAL, 'EN PODER DEL CLIENTE');
INSERT INTO SITUACION (INDSITTAR, DESCRIPCION) VALUES (SEQ_SITUACION_INDSITTAR.NEXTVAL, 'ACUSE RECIBO CLIENTE');
INSERT INTO SITUACION (INDSITTAR, DESCRIPCION) VALUES (SEQ_SITUACION_INDSITTAR.NEXTVAL, 'OPERATIVA');
INSERT INTO SITUACION (INDSITTAR, DESCRIPCION) VALUES (SEQ_SITUACION_INDSITTAR.NEXTVAL, 'BLOQUEADA ROBO');
INSERT INTO SITUACION (INDSITTAR, DESCRIPCION) VALUES (SEQ_SITUACION_INDSITTAR.NEXTVAL, 'CADUCADA');
INSERT INTO SITUACION (INDSITTAR, DESCRIPCION) VALUES (SEQ_SITUACION_INDSITTAR.NEXTVAL, 'BLOQUEDA PERDIDA');
INSERT INTO SITUACION (INDSITTAR, DESCRIPCION) VALUES (SEQ_SITUACION_INDSITTAR.NEXTVAL, 'DESTRUIDA');
INSERT INTO SITUACION (INDSITTAR, DESCRIPCION) VALUES (SEQ_SITUACION_INDSITTAR.NEXTVAL, 'BLOQUEADA FRAUDE');
INSERT INTO SITUACION (INDSITTAR, DESCRIPCION) VALUES (SEQ_SITUACION_INDSITTAR.NEXTVAL, 'INUTILIZABLE');
-- 5.3. Inserción en ENTIDAD Se insertan los registros en la tabla ENTIDAD.
-- Inserción en ENTIDAD (COD_BCO, BANCO)
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES (SEQ_ENTIDAD_COD_BCO.NEXTVAL, 'BANCOESTADO'); -- Debería ser 0 (START WITH 0)
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES (SEQ_ENTIDAD_COD_BCO.NEXTVAL, 'SCOTIABANK');  -- Debería ser 10
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES (SEQ_ENTIDAD_COD_BCO.NEXTVAL, 'SANTANDER');   -- Debería ser 20
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES (SEQ_ENTIDAD_COD_BCO.NEXTVAL, 'ITAU');        -- Debería ser 30
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES (SEQ_ENTIDAD_COD_BCO.NEXTVAL, 'BANCO DE CHILE');-- Debería ser 40

-- 5.4. Inserción en SUCURSAL Se insertan los registros en la tabla SUCURSAL. Se debe usar una combinación de un COD_BCO existente (por ejemplo, el primero insertado: 0) y el valor de la secuencia para COD_SUC.
-- Inserción en SUCURSAL (COD_BCO, COD_SUC, SUCURSAL)
-- Usaremos el COD_BCO 0 (BANCOESTADO) para los ejemplos de sucursales.

INSERT INTO SUCURSAL (COD_BCO, COD_SUC, SUCURSAL) VALUES (0, SEQ_SUCURSAL_COD_SUC.NEXTVAL, 'SANTIAGO CENTRO 1'); -- COD_SUC: 1
INSERT INTO SUCURSAL (COD_BCO, COD_SUC, SUCURSAL) VALUES (0, SEQ_SUCURSAL_COD_SUC.NEXTVAL, 'MACUL');           -- COD_SUC: 2
INSERT INTO SUCURSAL (COD_BCO, COD_SUC, SUCURSAL) VALUES (0, SEQ_SUCURSAL_COD_SUC.NEXTVAL, 'ÑUÑOA');           -- COD_SUC: 3
INSERT INTO SUCURSAL (COD_BCO, COD_SUC, SUCURSAL) VALUES (0, SEQ_SUCURSAL_COD_SUC.NEXTVAL, 'PUENTE ALTO');       -- COD_SUC: 4
INSERT INTO SUCURSAL (COD_BCO, COD_SUC, SUCURSAL) VALUES (0, SEQ_SUCURSAL_COD_SUC.NEXTVAL, 'RENCA');           -- COD_SUC: 5

-- 6. Ingresar Registros en Tablas Vacías

-- 6.1. Inserción en PERSONA
-- Inserción en PERSONA (RUT, NOMBRES, APE_PAT, APE_MAT)
INSERT INTO PERSONA (RUT, NOMBRES, APE_PAT, APE_MAT) VALUES (12345678, 'JUAN', 'PEREZ', 'GOMEZ');
INSERT INTO PERSONA (RUT, NOMBRES, APE_PAT, APE_MAT) VALUES (19876543, 'MARIA', 'LOPEZ', 'DIAZ');
INSERT INTO PERSONA (RUT, NOMBRES, APE_PAT, APE_MAT) VALUES (15000000, 'PEDRO', 'ROJAS', NULL); -- APE_MAT es opcional

-- 6.2. Inserción en CUENTA Se utiliza COD_BCO=0 y COD_SUC=1 (Bancoestado, Santiago Centro 1), CODESTCTA=5 (CASTIGADA), y RUT de personas existentes.
-- Inserción en CUENTA (COD_BCO, COD_SUC, NUMCONTRATO, CODESTCTA, FECALTA, FECBAJA, RUT)
-- CUENTA 1: JUAN PEREZ GOMEZ (RUT 12345678), Activa (CODESTCTA 1)
INSERT INTO CUENTA (COD_BCO, COD_SUC, NUMCONTRATO, CODESTCTA, FECALTA, FECBAJA, RUT)
VALUES (0, 1, 'CUE000012345', 1, DATE '2023-01-15', NULL, 12345678);

-- CUENTA 2: MARIA LOPEZ DIAZ (RUT 19876543), Castigada (CODESTCTA 5)
INSERT INTO CUENTA (COD_BCO, COD_SUC, NUMCONTRATO, CODESTCTA, FECALTA, FECBAJA, RUT)
VALUES (0, 1, 'CUE000012346', 5, DATE '2020-05-20', NULL, 19876543);

-- 6.3. Inserción en TARJETA Se utiliza la cuenta existente (COD_BCO=0, COD_SUC=1, NUMCONTRATO='CUE000012345') y INDSITTAR=5 (OPERATIVA). Se asume que ENTIDAD y SUCURSAL en TARJETA son los mismos que en CUENTA (0 y 1 respectivamente).
-- Inserción en TARJETA (ENTIDAD, SUCURSAL, NUMCONTRATO, PAN, INDSITTAR, FECADDU, TIPPER, RUT)
-- TARJETA 1: Para la CUENTA 1 (Juan Perez Gomez), Operativa (INDSITTAR 5)
INSERT INTO TARJETA (ENTIDAD, SUCURSAL, NUMCONTRATO, PAN, INDSITTAR, FECADDU, TIPPER, RUT)
VALUES ('0', '1', 'CUE000012345', '1234567890123456', 5, DATE '2028-12-31', 'DEBITO', 12345678);

-- TARJETA 2: Para la CUENTA 2 (Maria Lopez Diaz), Bloqueada Robo (INDSITTAR 6)
INSERT INTO TARJETA (ENTIDAD, SUCURSAL, NUMCONTRATO, PAN, INDSITTAR, FECADDU, TIPPER, RUT)
VALUES ('0', '1', 'CUE000012346', '9876543210987654', 6, DATE '2026-06-30', 'CREDITO', 19876543);
trabajofinal.sql
Mostrando trabajofinal.sql