-- 0. Crear BDD
DROP DATABASE IF EXISTS Banco;
CREATE DATABASE Banco;
USE Banco;

-- 1. Crear tablas:
-- ESTADO
CREATE TABLE ESTADO (
    CODESTCTA INT PRIMARY KEY,
    DESCRIPCION VARCHAR(30) NOT NULL
);
-- ENTIDAD
CREATE TABLE ENTIDAD (
    COD_BCO INT PRIMARY KEY,
    BANCO VARCHAR(30) NOT NULL
);
-- SUCURSAL
CREATE TABLE SUCURSAL (
    COD_SUC INT PRIMARY KEY,
    SUCURSAL VARCHAR(30) NOT NULL
);
-- SITUACION
CREATE TABLE SITUACION (
    INDSITUAR INT PRIMARY KEY,
    DESCRIPCION VARCHAR(20) NOT NULL
);
-- PERSONA
CREATE TABLE PERSONA (
    RUT INT PRIMARY KEY,
    NOMBRES VARCHAR(30) NOT NULL,
    APE_PAT VARCHAR(20) NOT NULL,
    APE_MAT VARCHAR(20)
);
-- CUENTA
CREATE TABLE CUENTA (
    COD_BCO VARCHAR(4),
    COD_SUC VARCHAR(4),
    NUMCONTRATO VARCHAR(12),
    CODESTCTA INT,
    FECALTA DATE NOT NULL,
    FECBAJA DATE,
    RUT INT,
    PRIMARY KEY (COD_BCO, COD_SUC, NUMCONTRATO, CODESTCTA)
);
-- TARJETA
CREATE TABLE TARJETA (
    ENTIDAD VARCHAR(4),
    SUCURSAL VARCHAR(4),
    NUMCONTRATO VARCHAR(12),
    PAN VARCHAR(16) PRIMARY KEY,
    INDSITUAR INT NOT NULL,
    FECCADU DATE NOT NULL,
    TIPPER VARCHAR(10) NOT NULL,
    RUT INT
);
-- 2. Crear restricciones (4) FOREIGN KEY
ALTER TABLE CUENTA ADD CONSTRAINT FK_CUENTA_ESTADO 
    FOREIGN KEY (CODESTCTA) REFERENCES ESTADO(CODESTCTA);

ALTER TABLE CUENTA ADD CONSTRAINT FK_CUENTA_PERSONA 
    FOREIGN KEY (RUT) REFERENCES PERSONA(RUT);

ALTER TABLE TARJETA ADD CONSTRAINT FK_TARJETA_SITUACION 
    FOREIGN KEY (INDSITUAR) REFERENCES SITUACION(INDSITUAR);

ALTER TABLE TARJETA ADD CONSTRAINT FK_TARJETA_PERSONA 
    FOREIGN KEY (RUT) REFERENCES PERSONA(RUT);
-- 3. Crear secuencias
-- Secuencia para ESTADO.CODESTCTA
CREATE SEQUENCE SEQ_ESTADO
    START WITH 1
    INCREMENT BY 1;

-- Secuencia para SITUACION.INDSITUAR
CREATE SEQUENCE SEQ_SITUACION
    START WITH 1
    INCREMENT BY 1;

-- Secuencia para ENTIDAD.COD_BCO
CREATE SEQUENCE SEQ_ENTIDAD
    -- START WITH 0
    START WITH 10
    INCREMENT BY 10;

-- Secuencia para SUCURSAL.COD_SUC
CREATE SEQUENCE SEQ_SUCURSAL
    START WITH 1
    INCREMENT BY 1;
-- 4. Insertar registros en ESTADO usando la secuencia
-- INSERT INTO ESTADO (CODESTCTA, DESCRIPCION) VALUES (SEQ_ESTADO.NEXTVAL, 'ACTIVA');
-- INSERT INTO ESTADO (CODESTCTA, DESCRIPCION) VALUES (SEQ_ESTADO.NEXTVAL, 'NO ACTIVA');
-- INSERT INTO ESTADO (CODESTCTA, DESCRIPCION) VALUES (SEQ_ESTADO.NEXTVAL, 'MOROSIDAD LEVE');
-- INSERT INTO ESTADO (CODESTCTA, DESCRIPCION) VALUES (SEQ_ESTADO.NEXTVAL, 'ACELERACIÓN');
-- INSERT INTO ESTADO (CODESTCTA, DESCRIPCION) VALUES (SEQ_ESTADO.NEXTVAL, 'CASTIGADA');
INSERT INTO ESTADO (CODESTCTA, DESCRIPCION) VALUES (NEXT VALUE FOR SEQ_ESTADO, 'ACTIVA');
INSERT INTO ESTADO (CODESTCTA, DESCRIPCION) VALUES (NEXT VALUE FOR SEQ_ESTADO, 'NO ACTIVA');
INSERT INTO ESTADO (CODESTCTA, DESCRIPCION) VALUES (NEXT VALUE FOR SEQ_ESTADO, 'MOROSIDAD LEVE');
INSERT INTO ESTADO (CODESTCTA, DESCRIPCION) VALUES (NEXT VALUE FOR SEQ_ESTADO, 'ACELERACIÓN');
INSERT INTO ESTADO (CODESTCTA, DESCRIPCION) VALUES (NEXT VALUE FOR SEQ_ESTADO, 'CASTIGADA');
-- 5. Insertar registros en SITUACION usando la secuencia
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (NEXT VALUE FOR SEQ_SITUACION, 'SOLICITADA');
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (NEXT VALUE FOR SEQ_SITUACION, 'IMPRESA');
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (NEXT VALUE FOR SEQ_SITUACION, 'EN PODER DEL CLIENTE');
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (NEXT VALUE FOR SEQ_SITUACION, 'ACUSE RECIBO CLIENTE');
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (NEXT VALUE FOR SEQ_SITUACION, 'OPERATIVA');
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (NEXT VALUE FOR SEQ_SITUACION, 'BLOQUEADA ROBO');
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (NEXT VALUE FOR SEQ_SITUACION, 'CADUCADA');
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (NEXT VALUE FOR SEQ_SITUACION, 'BLOQUEDA PERDIDA');
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (NEXT VALUE FOR SEQ_SITUACION, 'DESTRUIDA');
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (NEXT VALUE FOR SEQ_SITUACION, 'BLOQUEADA FRAUDE');
INSERT INTO SITUACION (INDSITUAR, DESCRIPCION) VALUES (NEXT VALUE FOR SEQ_SITUACION, 'INUTILIZABLE');
-- 6. Insertar registros en ENTIDAD usando la secuencia
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES (NEXT VALUE FOR SEQ_ENTIDAD, 'BANCOESTADO');
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES (NEXT VALUE FOR SEQ_ENTIDAD, 'SCOTIABANK');
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES (NEXT VALUE FOR SEQ_ENTIDAD, 'SANTANDER');
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES (NEXT VALUE FOR SEQ_ENTIDAD, 'ITAU');
INSERT INTO ENTIDAD (COD_BCO, BANCO) VALUES (NEXT VALUE FOR SEQ_ENTIDAD, 'BANCO DE CHILE');
-- 7. Insertar registros en SUCURSAL usando la secuencia
INSERT INTO SUCURSAL (COD_SUC, SUCURSAL) VALUES (NEXT VALUE FOR SEQ_SUCURSAL, 'SANTIAGO CENTRO 1');
INSERT INTO SUCURSAL (COD_SUC, SUCURSAL) VALUES (NEXT VALUE FOR SEQ_SUCURSAL, 'MACUL');
INSERT INTO SUCURSAL (COD_SUC, SUCURSAL) VALUES (NEXT VALUE FOR SEQ_SUCURSAL, 'ÑUÑOA');
INSERT INTO SUCURSAL (COD_SUC, SUCURSAL) VALUES (NEXT VALUE FOR SEQ_SUCURSAL, 'PUENTE ALTO');
INSERT INTO SUCURSAL (COD_SUC, SUCURSAL) VALUES (NEXT VALUE FOR SEQ_SUCURSAL, 'RENCA');
-- 8. Insertar registros en las tablas vacías (PERSONA, CUENTA, TARJETA)
INSERT INTO PERSONA (RUT, NOMBRES, APE_PAT, APE_MAT) VALUES (12345678, 'JUAN CARLOS', 'GONZALEZ', 'PEREZ');
INSERT INTO PERSONA (RUT, NOMBRES, APE_PAT, APE_MAT) VALUES (23456789, 'MARIA ISABEL', 'LOPEZ', 'SILVA');
INSERT INTO PERSONA (RUT, NOMBRES, APE_PAT, APE_MAT) VALUES (34567890, 'PEDRO ANTONIO', 'RODRIGUEZ', 'MARTINEZ');
INSERT INTO PERSONA (RUT, NOMBRES, APE_PAT, APE_MAT) VALUES (45678901, 'ANA MARIA', 'FERNANDEZ', 'GARCIA');
INSERT INTO PERSONA (RUT, NOMBRES, APE_PAT, APE_MAT) VALUES (56789012, 'CARLOS ALBERTO', 'RAMIREZ', 'CASTILLO');

-- Insertar cuentas
INSERT INTO CUENTA (COD_BCO, COD_SUC, NUMCONTRATO, CODESTCTA, FECALTA, FECBAJA, RUT) 
VALUES ('0010', '0001', 'CTO20240001', 1, SYSDATE(), NULL, 12345678);

INSERT INTO CUENTA (COD_BCO, COD_SUC, NUMCONTRATO, CODESTCTA, FECALTA, FECBAJA, RUT) 
VALUES ('0020', '0002', 'CTO20240002', 1, SYSDATE(), NULL, 23456789);

INSERT INTO CUENTA (COD_BCO, COD_SUC, NUMCONTRATO, CODESTCTA, FECALTA, FECBAJA, RUT) 
VALUES ('0030', '0003', 'CTO20240003', 2, SYSDATE(), NULL, 34567890);

-- Insertar tarjetas
-- INSERT INTO TARJETA (ENTIDAD, SUCURSAL, NUMCONTRATO, PAN, INDSITUAR, FECCADU, TIPPER, RUT) 
-- VALUES ('0010', '0001', 'CTO20240001', '4111111111111111', 5, TO_DATE('2026-12-31', 'YYYY-MM-DD'), 'TITULAR', 12345678);
INSERT INTO TARJETA (ENTIDAD, SUCURSAL, NUMCONTRATO, PAN, INDSITUAR, FECCADU, TIPPER, RUT) 
VALUES ('0010', '0001', 'CTO20240001', '4111111111111111', 5, STR_TO_DATE('2026-12-31', '%Y-%m-%d'), 'TITULAR', 12345678);

INSERT INTO TARJETA (ENTIDAD, SUCURSAL, NUMCONTRATO, PAN, INDSITUAR, FECCADU, TIPPER, RUT) 
VALUES ('0020', '0002', 'CTO20240002', '5111111111111111', 5, STR_TO_DATE('2027-06-30', '%Y-%m-%d'), 'TITULAR', 23456789);

INSERT INTO TARJETA (ENTIDAD, SUCURSAL, NUMCONTRATO, PAN, INDSITUAR, FECCADU, TIPPER, RUT) 
VALUES ('0030', '0003', 'CTO20240003', '6111111111111111', 1, STR_TO_DATE('2028-03-15', '%Y-%m-%d'), 'ADICIONAL', 34567890);

-- Confirmar los cambios
COMMIT;

-- Verificar los registros insertados
-- Verificar los registros insertados
SELECT 'ESTADO' AS TABLA, COUNT(*) AS CANTIDAD FROM ESTADO
UNION ALL
SELECT 'ENTIDAD', COUNT(*) FROM ENTIDAD
UNION ALL
SELECT 'SUCURSAL', COUNT(*) FROM SUCURSAL
UNION ALL
SELECT 'SITUACION', COUNT(*) FROM SITUACION
UNION ALL
SELECT 'PERSONA', COUNT(*) FROM PERSONA
UNION ALL
SELECT 'CUENTA', COUNT(*) FROM CUENTA
UNION ALL
SELECT 'TARJETA', COUNT(*) FROM TARJETA;

DROP DATABASE IF EXISTS Banco;
DROP DATABASE IF EXISTS emprendimiento; -- extra
DROP DATABASE IF EXISTS evaluacion_grupal;
DROP DATABASE IF EXISTS datosrelacional;
DROP DATABASE IF EXISTS prueba;
DROP DATABASE IF EXISTS estado;